AIP/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path , include
from . import views
from django.views.generic.base import TemplateView # new

app_name = 'AIP'

urlpatterns = [
    path('', views.index, name='index'),
    path('pickskill/', views.pickskill, name='pickskill'),
    path('begin/', views.begin, name='begin'),
    path('quiz/', views.quiz, name='quiz'),
    path('quizsimple/', views.quizsimple, name='quizsimple'),
    path('upload/', views.upload, name='upload'),
    path('comment/', views.comment, name='comment'),
    path('question/', views.question, name='question'),
    path('logout/', views.logout, name='logout'),
    path('export/', views.export, name='export'),
    path('add/', views.add, name='add'),
    path('questionupload/', views.questionupload, name='questionupload'),
    path('scores/', views.scores, name='scores'),
    path('quizzes/', views.quizzes,name='quizzes'),
    path('addquiz/', views.addquiz,name='addquiz'),
    path('addquestion/', views.addquestion, name='addquestion'),
    path('addquestion1/', views.addquestion1, name='addquestion1'),
    path('quizlist/', views.quizbucket, name='quizbucket'),
    path('quiz/<int:pk>/', views.takequiz, name='takequiz'),
    path('searchquiz/<int:pk>/', views.searchquiz, name='searchquiz'),
    path('scores/<int:pk>/', views.scores, name='scores'),
    path('review/', views.review, name='review'),
    path('review/<str:pk>/', views.reviewquiz, name='reviewquiz'),
    path('markattendance/<int:pk>/', views.markattendance, name='markattendance'),
    path('showattendance/<int:pk>/', views.showattendance, name='showattendance'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Portal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("AIP.urls")),
    path('accounts/', include('allauth.urls')),

]

AIP/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Attendance(models.Model):
    trainer_name                     = models.CharField(max_length=200,default='')
    trainee_emails                   = models.TextField(null=True)
    expire_time                      = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.trainer_name

class Trainee_Attendance(models.Model):
    trainee_email                    = models.CharField(max_length=100,default='')
    login_time                       = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.trainee_email


class Quiz(models.Model):
    quiz_name                        = models.CharField(max_length=100,default='')
    quiz_OrgIdentifier               = models.CharField(max_length=40,default='')
    quiz_questions                   = models.TextField(null=True)
    quiz_noofquest                   = models.IntegerField(default=0)

    def __str__(self):
        return self.quiz_name + "_" + self.quiz_OrgIdentifier

class Question(models.Model):
    q_subject                    = models.CharField(max_length=40)
    q_cat                        = models.CharField(max_length=40)
    q_rank                       = models.CharField(max_length=20)
    q_text                       = models.TextField(null=True,default='')
    q_option1                    = models.CharField(max_length=200,default='')
    q_option2                    = models.CharField(max_length=200,default='')
    q_option3                    = models.CharField(max_length=200,default='')
    q_option4                    = models.CharField(max_length=200,default='')
    q_answer                     = models.CharField(max_length=20)
    q_ask_time                   = models.DateTimeField(default=datetime.now, blank=True)
    no_times_ques_served         = models.IntegerField(default=0)
    no_times_anwered_correctly   = models.IntegerField(default=0)
    no_times_anwered_incorrectly = models.IntegerField(default=0)
    difficulty_score             = models.DecimalField(default=0,max_digits = 5, decimal_places = 2)

    def __str__(self):
        return self.q_text

class Answer(models.Model):
    question                     = models.ForeignKey(Question, on_delete=models.CASCADE)
    ans_option                   = models.CharField(max_length=20)
    is_correct                   = models.BooleanField(default=False)
    ans_time                     = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.ans_option

class Result(models.Model):
    c_user                      = models.CharField(max_length=100)
    c_email                     = models.CharField(max_length=100,default='')
    c_quiz_name                 = models.CharField(max_length=100,default='')
    c_tot_score                 = models.IntegerField(default=0)
    c_cat_scores                = models.TextField(null=True,default=0)
    c_comment                   = models.TextField(null=True,default='')
    c_new_quest                 = models.TextField(null=True,default='')
    c_attempt_date              = models.DateTimeField(default=datetime.now, blank=True)
    c_total_q_asked             = models.IntegerField(default=0)
    c_total_ans_correct         = models.IntegerField(default=0)
    c_total_ans_incorrect       = models.IntegerField(default=0)

    def __str__(self):
        return self.c_user

AIP/forms.py
from django.db import models

from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        labels = {
            'q_subject'                     : 'Subject',
            'q_cat'                         : 'Category',
            'q_rank'                        : 'Rank',
            'q_text'                        : 'Question',
            'q_option1'                     : 'Answer Option1',
            'q_option2'                     : 'Answer Option2',
            'q_option3'                     : 'Answer Option3',
            'q_option4'                     : 'Answer Option4',
            'q_answer'                      : 'Answer',
        }

        fields = ('q_subject','q_cat','q_rank','q_text','q_option1','q_option2','q_option3','q_option4','q_answer')
        #fields = '__all__'

AIP/views.py
import datetime
from datetime import timedelta
import os
import pprint
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
from django.db.models import Count
import pandas as pd
from django.conf import settings
from django.http import HttpResponse, request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect, resolve_url
from django.utils.datastructures import MultiValueDictKeyError
from django.core.files.storage import FileSystemStorage
from django.views import generic
from django.urls import reverse
from .models import Question, Answer, Result,Quiz,Attendance,Trainee_Attendance
from django.http import HttpResponse
import json
import random
import csv, io
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from .forms import QuestionForm
from django.contrib.auth.models import User
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,UpdateView)


def index(request):
    quizname = request.session.get('quizname',None)
    #quizattend = request.session['fromattend']
    #return HttpResponse(quizname)

    if quizname is None:
        #settings.LOGIN_REDIRECT_URL = '/pickskill'
        #return render(request, 'AIP/index.html')
        settings.LOGIN_REDIRECT_URL = '/'
        return render(request, 'AIP/success.html')
    else:
        return redirect('AIP:takequiz', pk=quizname)


def pickskill(request):
    request.session['user'] = request.user.get_full_name()
    request.session['email'] = request.user.email
    user = request.session['user']
    email = request.session['email']
    Result.objects.create(c_user=user,c_email=email)
    category_count = Question.objects.values('q_rank').order_by('q_rank').annotate(count=Count('q_rank'))
    cat_count = list(category_count)
    categories = []
    for item in cat_count:
        cnt = str(item['count'])
        line = item['q_rank'] + ' (' + cnt + ')'
        categories.append(line)

    context = {'user':user,'categories':categories}
    return render(request, 'AIP/pickskill.html',context)

def begin(request):
    if request.method == 'POST':
        subject = request.POST['skill']
        rank = request.POST['proficiency']
        context = {'subject': subject, 'rank': rank}
        request.session['skill'] = subject
        request.session['proficiency'] = rank
        request.session['curr_difficulty_score'] = 1
        request.session['total_q_asked'] = 1
        request.session['total_q_ans_correct'] = 0
        request.session['counter'] = 0
        cat_dict = {'Introduction': 0, 'Syntax': 0, 'OOPS': 0, 'NativeDataTypes': 0, 'FileAndExceptionHandling': 0,
                    'Function': 0, 'Advanced': 0,'All': 0}
        request.session['cat_dict'] = cat_dict
        request.session['score'] = 0

        if rank == 'Adaptive':
            return render(request, 'AIP/begin.html', context)
        else:
            return render(request, 'AIP/beginsimple.html', context)


def quizsimple(request):
    subject = request.session['skill']
    rank = request.session['proficiency']
    total_q_asked = request.session['total_q_asked']
    total_q_ans_correct = request.session['total_q_ans_correct']
    counter = request.session['counter']
    score = request.session['score']
    cat_dict = request.session['cat_dict']
    user = request.session['user']

    questions = Question.objects.filter(q_subject=subject, q_rank=rank)
    max = Question.objects.filter(q_subject=subject, q_rank=rank).count()
    ind = random.randint(1, max)
    #return  HttpResponse(ind)
    question = questions[ind]
    #question = questions[0]
    context = {'total_q_asked': total_q_asked, 'question': question}
    if request.method == 'POST':
        option = request.POST.get('options')
        q = Question(question.pk)
        ans = Answer()
        ans.question = q
        question.no_times_ques_served += 1

        total_q_asked += 1
        if question.q_answer == option:
            ans.ans_option = option
            ans.is_correct = True
            question.no_times_anwered_correctly += 1
            total_q_ans_correct += 1
            cat_dict[question.q_cat] += 1
            ans.save()
        else:
            ans.ans_option = option
            ans.is_correct = False
            question.no_times_anwered_incorrectly += 1
            ans.save()

        Question.objects.filter(pk=q.pk).update(no_times_ques_served=question.no_times_ques_served,
                                                no_times_anwered_correctly=question.no_times_anwered_correctly,
                                                no_times_anwered_incorrectly=question.no_times_anwered_incorrectly)
        if counter == (max-1) or request.POST.get('END') == 'STOP':
            score1 = (total_q_ans_correct / (total_q_asked - 1)) * 100
            score = round(score1)
            cat_scores = json.dumps(cat_dict)
            total_ans_incorrect = ((total_q_asked - 1) - total_q_ans_correct)
            Result.objects.filter(c_user=user).update(c_tot_score=score)
            Result.objects.filter(c_user=user).update(c_cat_scores=cat_scores,c_total_q_asked=(total_q_asked-1),c_total_ans_correct=total_q_ans_correct,c_total_ans_incorrect=total_ans_incorrect)
            score_context = {'score': score, 'cat_dict': cat_dict, 'total_q_asked': total_q_asked - 1,
                             'total_q_ans_correct': total_q_ans_correct}
            return render(request, 'AIP/report.html', score_context)

        counter += 1
        request.session['score'] = score
        request.session['counter'] = counter
        request.session['total_q_asked'] = total_q_asked
        request.session['total_q_ans_correct'] = total_q_ans_correct
        request.session['cat_dict'] = cat_dict

        questions = Question.objects.filter(q_subject=subject, q_rank=rank)
        max = Question.objects.filter(q_subject=subject, q_rank=rank).count()
        ind = random.randint(1, max)
        question = questions[ind]
        context = {'total_q_asked': total_q_asked, 'question': question}
        return render(request, 'AIP/quizsimple.html', context)
    else:
        # this is GET flow of 1st question
        return render(request, 'AIP/quizsimple.html', context)


def quiz(request):
    subject = request.session['skill']
    rank = request.session['proficiency']
    curr_difficulty_score = request.session['curr_difficulty_score']
    total_q_asked = request.session['total_q_asked']
    total_q_ans_correct = request.session['total_q_ans_correct']
    score = request.session['score']
    cat_dict = request.session['cat_dict']
    user = request.session['user']
    counter = request.session['counter']

    questions = Question.objects.filter(q_subject=subject, q_rank=rank).filter(difficulty_score__gt=curr_difficulty_score).order_by('difficulty_score')
    question = questions[0]
    context = {'total_q_asked': total_q_asked, 'question': question}

    if request.method == 'POST':
        option = request.POST.get('options')
        q = Question(question.pk)
        ans = Answer()
        ans.question = q
        question.no_times_ques_served += 1
        total_q_asked += 1
        if question.q_answer == option:
            ans.ans_option = option
            ans.is_correct = True
            question.no_times_anwered_correctly += 1
            total_q_ans_correct += 1
            cat_dict[question.q_cat] += 1
            ans.save()
        else:
            ans.ans_option = option
            ans.is_correct = False
            question.no_times_anwered_incorrectly += 1
            ans.save()

        Question.objects.filter(pk=q.pk).update(no_times_ques_served=question.no_times_ques_served,
                                                no_times_anwered_correctly=question.no_times_anwered_correctly,
                                                no_times_anwered_incorrectly=question.no_times_anwered_incorrectly,
                                                difficulty_score=curr_difficulty_score)

        if counter == 4 or request.POST.get('END') == 'STOP':
            score1 = (total_q_ans_correct / (total_q_asked - 1)) * 100
            score = round(score1)
            cat_scores = json.dumps(cat_dict)
            total_ans_incorrect = ((total_q_asked - 1) - total_q_ans_correct)

            Result.objects.filter(c_user=user).update(c_tot_score=score)
            Result.objects.filter(c_user=user).update(c_cat_scores=cat_scores, c_total_q_asked=(total_q_asked-1),
                                                      c_total_ans_correct=total_q_ans_correct,
                                                      c_total_ans_incorrect=total_ans_incorrect)
            score_context = {'score': score, 'cat_dict': cat_dict, 'total_q_asked': total_q_asked - 1,
                             'total_q_ans_correct': total_q_ans_correct}
            return render(request, 'AIP/report.html', score_context)

        counter += 1
        request.session['counter'] = counter
        request.session['score'] = score
        request.session['total_q_asked'] = total_q_asked
        request.session['total_q_ans_correct'] = total_q_ans_correct
        request.session['curr_difficulty_score'] = curr_difficulty_score
        request.session['cat_dict'] = cat_dict

        # curr_difficulty_score = question.no_times_anwered_incorrectly / question.no_times_anwered_incorrectly + question.no_times_anwered_correctly
        curr_difficulty_score = question.no_times_anwered_incorrectly / question.no_times_ques_served
        questions = Question.objects.filter(q_subject=subject, q_rank=rank).filter(
            difficulty_score__gt=curr_difficulty_score).order_by('difficulty_score')
        question = questions[0]
        context = {'total_q_asked': total_q_asked, 'question': question}
        return render(request, 'AIP/quiz.html', context)
    else:

AIP/templates/AIP/add.html
<h2>New Question</h2>
      <form method="POST">{%  csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="save btn btn-default">Add Question</button>
      </form>

AIP/templates/AIP/addquestion1.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,700" rel="stylesheet">
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
   {{addquestion}}
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                  <div class="row">
                     <form id="form" name="form" method="post">{%  csrf_token %}
                       <p><strong>Select and Add the Question</strong></p>
                         <select  name = drop1>
                             {% for question in questions %}
                                  <option value="{{ question }}">{{ question }}</option>
                             {% endfor %}
                         </select>
                        <p></p>
                         <input type="submit" name="BEGIN" value= "Add ->" class="btn btn-white"/> &nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="submit" name="END" value= "STOP" class="btn btn-white"/> &nbsp;&nbsp;&nbsp;&nbsp;
                     </form>
                  </div>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/begin.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                  <div class="row">
                     <p><h2><strong> Welcome !! You have selected {{subject}} in <i>{{rank}} </i> mode<strong></h2></p>
                     <p><strong> <i>This will be a multiple choice quiz and the questions will be dynamically enhanced based on your progress</i><strong></p>
                     <p><strong> <i>This is not a timed test , you can stop the test at any point you wish to <p><strong> <i>
                     <div class="col-md-7 copy animate-box">
                        <a href="{% url 'AIP:quiz' %}"class="btn btn-white">Start quiz</a>
                        <p></p>
                          <a style="color: #8C001A" href="/logout" >Logout</a>
                  </div>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/beginsimple.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                  <div class="row">
                     <p><h2><strong> Welcome !! You have selected {{subject}} in <i>{{rank}} </i> mode<strong></h2></p>
                     <p><strong> <i>This will be a multiple choice quiz with total 30 questions </i><strong></p>
                     <p><strong> <i>This is not a timed test , you can stop the test at any point you wish to <p><strong> <i>
                     <div class="col-md-7 copy animate-box">
                        <a href="{% url 'AIP:quizsimple' %}"class="btn btn-white">Start quiz</a>
                        <p></p>
                          <strong> <a style="color: #8C001A" href="/logout" ">Logout</a></strong>
                    </div>
                  </div>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/compare.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE HTML>
<!--
   QuizHop
   -->
<html>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                   <p><strong><i style="color:#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{subject}}  &nbsp; : &nbsp;&nbsp; {{category}} </i></strong></p>
                   <p><strong><i style="color:#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total Questions : {{total}} </i></strong></p>
                       <div class="col-md-7 copy animate-box">
                        <ol>
                             {% for question in questions %}
                             <div class="modal-header" >
                             <h3><span class="label label-warning" id="qid"></span><pre> Q ~ {{ question.q_text }} </pre></h3>
                             </div>
                             <div class="modal-body" style="color:#008080">
                               <label class="option1" >  {{ question.q_option1 }}</label>
                               <p></p>
                               <label class="option2">   {{ question.q_option2 }}</label>
                               <p></p>
                               <label class="option3">   {{ question.q_option3 }}</label>
                               <p></p>
                               <label class="option4">   {{ question.q_option4 }}</label>

                             </div>
                             <div class="modal-footer text-muted">
                               <pre>A ~ {{ question.q_answer }}  </pre>
                             </div>
                             {% endfor %}
                          </ol>
                           <p></p>
                        </div>
                   </form>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/markattendance.html
{% load static %}
<!DOCTYPE HTML>
<!--
  QuizHop
   -->
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> Quiz Hop </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Adaptive Interview Poral" />
      <!-- Animate.css -->
      <link rel="stylesheet" href="{% static 'css/animate.css'%}">
      <!-- Icomoon Icon Fonts-->
      <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
      <!-- Themify Icons-->
      <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
      <!-- Bootstrap  -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
      <!-- Theme style  -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
   </head>
   <body>
      <div class="gtco-loader"></div>
      <div id="page">
         <header id="gtco-header" class="gtco-cover" role="banner">
            <div class="gtco-container">
               <div class="display-tc">
                        <form method ="post">{%csrf_token%}
                           <b style="color:#000000">Training by :</b><br>
                           <textarea rows=1 cols=40  name="trainer" required></textarea><br>
                           <b style="color:#000000">Emails:</b><br>
                           <textarea rows=3 cols =40  name="trainees" required></textarea>
                           <p></p>
                           <b><label style="color:#000000" for="expires">Expires By:</label></b>
                           <input type="datetime-local" id="expires" name="expires"> <br>
                           <p></p>
                           <input type="submit"  name="Mark Attendance"  value="Mark Attendance" class="btn btn-white">
                        </form>
               </div>
            </div>
         </header>
      </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <!-- jQuery Easing -->
      <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <!-- Waypoints -->
      <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
      <!-- Carousel -->
      <script src="{% static 'js/owl.carousel.min.js'%}"></script>
      <!-- Magnific Popup -->
      <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'js/magnific-popup-options.js'%}"></script>
      <!-- Main -->
      <script src="{% static 'js/main.js' %}"></script>
      </div>
   </body>
</html>

AIP/templates/AIP/question_upload.html
{% if messages %}
    {% for message in messages %}
        <div>
            <strong>{{message|safe}}</strong>
        </div>
    {% endfor %}
{% else %}
{{order}}
<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <label > Upload a file </label>
    <input type ="file" name="file">
    <p>Only accepts CSV files</p>
    <button type="submit">Upload</button>
</form>
{% endif %}